name: JSQMessagesViewController
options:
  bundleIdPrefix: com.hexedbits.JSQMessages
  deploymentTarget:
    iOS: "11.0"
targets:
  JSQMessages:
    platform: iOS
    scheme: {} # Generate default scheme
    sources:
      - path: JSQMessagesViewController
    type: framework