#!/bin/sh -e

rm -rf Carthage/Build/iOS

carthage bootstrap --platform iOS --no-use-binaries --no-build

rm -f ./Carthage/Checkouts/facebook-ios-sdk/FBSDKIntegrationTests/FBSDKIntegrationTests.xcodeproj/xcshareddata/xcschemes/FBSDKIntegrationTests.xcscheme

./Scripts/static_carthage "$@" --platform iOS --no-use-binaries